name: bank-note-auth-feature-and-prediction-pipelines

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
       
      - name: Add execute permission to script
        run: chmod +x ./src/scripts/run-feature-and-prediction-pipelines.sh 

      - name: Execute Python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: ./src/scripts/run-feature-and-prediction-pipelines.sh

        
      - name: publish github pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./ # Change to the folder where your static files are generated
          #token: ${{ secrets.ACCESS_TOKEN }} # Replace with your own access token
          #cname: yourcustomdomain.com # Optional custom domain
          commit_message: Deploy the latest changes
          enable_jekyll: true
        
